sudo: required
language: generic
service:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t akshaykmr080/react-frontend .
script:
  - docker run -e CI=true akshaykmr080/react-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-137991398143"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
