FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

# This statement is not required as we will be using volumes.
# Leaving it here for backward compatibility
COPY . .

CMD ["npm", "run", "start"]