FROM node:alpine as builder
WORKDIR '/app'
COPY package.json .
RUN npm install
# This statement is not required as we will be using volumes.
# Leaving it here for backward compatibility
COPY . .
RUN npm run build


FROM nginx
COPY --from=builder /app/build /usr/share/nginx/html

